"""Initial tables

Revision ID: 474244523232
Revises: 
Create Date: 2026-08-11 13:07:51.723800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474244523232'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_no', sa.String(length=20), nullable=False),
    sa.Column('randomization_no', sa.String(length=20), nullable=True),
    sa.Column('name_abbr', sa.String(length=10), nullable=False),
    sa.Column('center_id', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('withdrawal_reason', sa.String(length=50), nullable=True),
    sa.Column('withdrawal_date', sa.String(length=20), nullable=True),
    sa.Column('completion_summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_center_status', 'patients', ['center_id', 'status'], unique=False)
    op.create_index(op.f('ix_patients_center_id'), 'patients', ['center_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_randomization_no'), 'patients', ['randomization_no'], unique=True)
    op.create_index(op.f('ix_patients_screening_no'), 'patients', ['screening_no'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('center_id', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('adverse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('drug_relation', sa.Integer(), nullable=False),
    sa.Column('drug_measure', sa.Integer(), nullable=False),
    sa.Column('other_measure', sa.Integer(), nullable=False),
    sa.Column('other_measure_detail', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.Integer(), nullable=False),
    sa.Column('is_sae', sa.Boolean(), nullable=True),
    sa.Column('sae_type', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adverse_events_id'), 'adverse_events', ['id'], unique=False)
    op.create_index(op.f('ix_adverse_events_patient_id'), 'adverse_events', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('concomitant_meds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('indication', sa.String(length=200), nullable=True),
    sa.Column('dosage_form', sa.String(length=100), nullable=True),
    sa.Column('dosage_amount', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=True),
    sa.Column('drug_relation', sa.String(length=100), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concomitant_meds_id'), 'concomitant_meds', ['id'], unique=False)
    op.create_index(op.f('ix_concomitant_meds_patient_id'), 'concomitant_meds', ['patient_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('visit_no', sa.String(length=10), nullable=False),
    sa.Column('visit_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_visit', 'visits', ['patient_id', 'visit_no'], unique=False)
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_index('idx_patient_visit', table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_concomitant_meds_patient_id'), table_name='concomitant_meds')
    op.drop_index(op.f('ix_concomitant_meds_id'), table_name='concomitant_meds')
    op.drop_table('concomitant_meds')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_adverse_events_patient_id'), table_name='adverse_events')
    op.drop_index(op.f('ix_adverse_events_id'), table_name='adverse_events')
    op.drop_table('adverse_events')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_screening_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_randomization_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_center_id'), table_name='patients')
    op.drop_index('idx_center_status', table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
